### PR TITLE
added book methods and label method

### PR DESCRIPTION
**Pull request by fickryiman**
- Create a list_all_books method under the book class
- Create add_book method under book class
- Create list_all_books_label method under label class
- added all methods into the main.rb through book_app.rb

### CODE REVIEW

**Comment by rbd3** [comment]
Hey @fickryiman ,
Good job for your project.
- There is one thing you need to check. when i add new book, the title i entered became the label but when i select 4. book label, it returns 'no label added'. Kindly fix that .

**Comment by fickryiman** [comment]
Hi @rbd3,

To Add a Book, please select 7, not 4.
4 is for list all books label.

image

**Comment by rbd3** [comment]
If you don't yet have a method to add a book label, your project work perfectly.
It's time to merge it

**Review by rbd3 — APPROVED** [review]
Good job!
It's time to merge it

**Pull request merged**
